# docker-compose.yml

version: "3.7"
services:
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        ports: 
        - '5431:5432'
        volumes:
        - postgres-db:/var/lib/postgresql/data
    app:
        build: .
        environment:
            DB_SCHEMA: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: postgres
        depends_on:
            - postgres
        ports:
            - '3000:3000'
        command: 'npm run start'
volumes:
  postgres-db: